export const AdminActionTypes = {
    SET_ALL_SELECTED: 'SET_ALL_SELECTED',
    SET_PENDING_SELECTED: 'SET_PENDING_SELECTED',
    SET_CONFIRM_SELECTED: 'SET_CONFIRM_SELECTED',
    SET_CANCEL_SELECTED: 'SET_CANCEL_SELECTED'
};